# Generated by Django 5.0.7 on 2024-10-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadagronomicosfilesmodel',
            name='file',
            field=models.FileField(upload_to='agronomicos'),
        ),
    ]
