# Generated by Django 5.0.7 on 2024-10-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
