# Generated by Django 5.0.7 on 2024-10-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_uploadfiles_addressmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFiles',
            new_name='UploadFilesModel',
        ),
    ]
