# Generated by Django 5.0.7 on 2024-10-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_uploadfilesmodel_my_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilesmodel',
            old_name='my_file',
            new_name='file',
        ),
    ]
