# Generated by Django 5.0.7 on 2024-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_rename_my_file_uploadfilesmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='parroquia',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
