# Generated by Django 5.0.7 on 2024-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_addressmodel_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='parroquia',
            field=models.CharField(max_length=100),
        ),
    ]
